### PR TITLE
adds basic chefspec support

### PR DESCRIPTION
**Pull request by dfinninger**
I had to write a lot of chefSpec this week and I thought adding some support for basic, repetitive things would be useful.

### CODE REVIEW

**Comment by vinyar** [comment]
that's cool!

**Comment by cabeca** [comment]
Sorry for the delay, but I took a long vacation and was away from GitHub for a while.
Regarding your contribution, I really appreciate it, but I'm trying to keep this package as small and focused as possible.
What I would recommend you to do is to make your own `SublimeChefSpec` package with these (and other future snippets) and submit it to Package Control. What do you think?

**Comment by dfinninger** [comment]
Sure, that works for me. I use this package a lot and I wanted to offer it
to you before rolling my own package.

**Comment by vinyar** [comment]
@dfinninger good luck. I'll watch for it (im currently using the merged branch locally)

**Pull request closed without merging**
